from enum import Enum


class StructuralComponentType(str, Enum):
    BRIDGE = "bridge"
    SUPERSTRUCTURE = "superstructure"
    SPAN = "span"
    LONGITUDINAL_MEMBERS = "longitudinal-members"
    GIRDER = "girder"
    REINFORCEMENT_GROUP = "reinforcement-group"
    PRIMARY_REINFORCEMENT = "primary-reinforcement"
    SECONDARY_REINFORCEMENT = "secondary-reinforcement"
    SHEAR_REINFORCEMENT = "shear-reinforcement"
    TENDON_GROUP = "tendon-group"
    INDIVIDUAL_TENDON = "individual-tendon"
    EDGE_BEAM = "edge-beam"
    TRANSVERSE_MEMBERS = "transverse-members"
    DECK_SLAB = "deck-slab"
    DIAPHRAGM = "diaphragm"
    TRANSVERSE_BRACING = "transverse-bracing"
    BRACE = "brace"
    CHORD = "chord"
    PLAN_BRACING = "plan-bracing"
    SUBSTRUCTURE = "substructure"
    SUPPORT = "support"
    ABOVE_GROUND = "above-ground"
    VERTICAL_MEMBERS = "vertical-members"
    PIER = "pier"
    WALL = "wall"
    HORIZONTAL_MEMBERS = "horizontal-members"
    CROSSBEAM = "crossbeam"
    BELOW_GROUND = "below-ground"
    PILE = "pile"
    PILE_CAP = "pile-cap"
    GROUND_BEAM = "ground-beam"
    SPREAD_FOOTING = "spread-footing"
    LINKAGE = "linkage"
    SUPERSTRUCTURE_TO_SUBSTRUCTURE_CONNECTIONS = "superstructure-to-substructure-connections"
    SUBSTRUCTURE_CONNECTIONS = "substructure-connections"
    SUPERSTRUCTURE_CONNECTIONS = "superstructure-connections"
    DECK_SLAB_CONNECTIONS = "deck-slab-connections"
    BRACING_CONNECTIONS = "bracing-connections"
    PLAN_BRACING_CONNECTIONS = "plan-bracing-connections"
    TRANSVERSE_BRACING_CONNECTIONS = "transverse-bracing-connections"
    SEGMENT = "segment" #universal group for grouping elements not listed above